### ISSUE TITLE
Random request being cached by cloudflare and returns same result

### ISSUE THREAD

**Issue by KravetsArtem** [openbrewerydb/openbrewerydb-rails-api#127]
# Bug Report

## Describe the bug

Random endpoint being cached by Cloudflare (according to headers in response for 24h). Which makes this API call useful once a day.

Not sure if it is intentional, I believe that makes the `random` endpoint a bit useless.

## Steps to reproduce bug

1. Go to [Open Brewery DB](https://www.openbrewerydb.org/documentation#random-brewery)
2. Click on `Run` for a random request 
3. It will always return the same result, in dev tools response headers you will see:
```
cache-control: public, max-age=86400
cf-cache-status: HIT
```

### Expected behavior

Disable caching for `/random` endpoint

## Screenshots

<img width="757" alt="image" src="https://github.com/openbrewerydb/openbrewerydb-rails-api/assets/32468018/ad38b158-1ebb-4c24-9718-dba922361bf6">

## Additional context

Passing `Cache-Control: 'no-cache'` with a request does not help

**Comment by chrisjm** [comment]
Thanks for the bug report @KravetsArtem. Not intentional; I just screwed up ([Halon's Razor](https://en.wikipedia.org/wiki/Hanlon%27s_razor) 🙂). 

Test it out, but works now for me. 

Previous:
<img width="1029" alt="CleanShot 2023-05-21 at 18 03 11@2x" src="https://github.com/openbrewerydb/openbrewerydb-rails-api/assets/96110/962ff3b6-db08-471b-b6c1-d0050eaf8dee">

Current:
<img width="1035" alt="CleanShot 2023-05-21 at 18 14 32@2x" src="https://github.com/openbrewerydb/openbrewerydb-rails-api/assets/96110/8098904f-c262-405e-a545-3aea5c8666a1">

![CleanShot 2023-05-21 at 18 13 49@2x](https://github.com/openbrewerydb/openbrewerydb-rails-api/assets/96110/ee05b1b2-d6c1-47c8-8bf6-fb94c95789f6)
